In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv("Hitters1.csv")
df.head()

Price   Demand
0     3.0    6791
1     3.6    5988
2    40.0     354
3    21.0     651
4     4.0    7111

In [3]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values
X,y

(array([ 3. ,  3.6, 40. , 21. ,  4. , 30. , 29. , 18. ,  9. ,  6. ,  5. ,
         8. , 15. , 32. , 20. , 10. , 17. ,  7. , 39. ,  4. , 35. , 39. ,
        44. , 40. , 25. ,  8. ,  5. ,  8. , 10. , 14. , 26. ]),
 array([6791, 5988,  354,  651, 7111,  406,  577,  655, 2891, 5589, 6707,
        4081, 2702,  370, 1251, 3140, 2469, 4909,  396, 7017,  484,  297,
         141,  193, 2801, 3731, 7444, 3910, 2678, 1833, 2946]))

In [5]:
regressor = LinearRegression()
regressor.fit(X.reshape(-1,1),y)

LinearRegression()

In [6]:
y_pred = regressor.predict(X.reshape(-1,1))
y_pred

array([ 5369.73357604,  5275.11305171,  -465.19875726,  2531.11784633,
        5212.03270216,  1111.80998147,  1269.51085534,  3004.22046794,
        4423.5283328 ,  4896.63095442,  5054.33182829,  4581.22920667,
        3477.32308956,   796.40823373,  2688.8187202 ,  4265.82745893,
        3161.92134182,  4738.93008054,  -307.49788338,  5212.03270216,
         323.30561211,  -307.49788338, -1096.00225275,  -465.19875726,
        1900.31435084,  4581.22920667,  5054.33182829,  4581.22920667,
        4265.82745893,  3635.02396344,  1742.61347696])

In [8]:
r2_score(y,y_pred=y_pred)

0.7338976168337804

In [9]:
y_new = np.sqrt(y)
y_new

array([82.40752393, 77.38216849, 18.81488772, 25.51470164, 84.32674546,
       20.14944168, 24.0208243 , 25.59296778, 53.76802024, 74.75961477,
       81.89627586, 63.88270501, 51.98076567, 19.23538406, 35.36947837,
       56.0357029 , 49.689033  , 70.06425622, 19.89974874, 83.76753548,
       22.        , 17.23368794, 11.87434209, 13.89244399, 52.92447449,
       61.08191222, 86.27861844, 62.5299928 , 51.74939613, 42.81354926,
       54.27706698])

In [18]:
regressor1 = LinearRegression()
regressor1.fit(X.reshape(-1,1),y_new)

regressor1.coef_, regressor1.intercept_

(array([-1.68932556]), 79.54515270075692)

In [19]:
y_pred1 = regressor1.predict(X.reshape(-1,1))
y_pred1

array([74.47717601, 73.46358068, 11.97213021, 44.06931589, 72.78785045,
       28.86538583, 30.5547114 , 49.13729258, 64.34122264, 69.40919933,
       71.09852489, 66.0305482 , 54.20526927, 25.48673471, 45.75864146,
       62.65189708, 50.82661814, 67.71987377, 13.66145577, 72.78785045,
       20.41875802, 13.66145577,  5.21482796, 11.97213021, 37.31201364,
       66.0305482 , 71.09852489, 66.0305482 , 62.65189708, 55.89459483,
       35.62268808])

In [20]:
r2_score(y_new,y_pred1)

0.8308606126447352

In [21]:
from sklearn.model_selection import train_test_split;
X_train,X_test,y_train,y_test = train_test_split(X.reshape(-1,1),y,test_size=0.2,random_state=42)

In [23]:
model_fit = LinearRegression()
model_fit.fit(X_train,y_train)

LinearRegression()

In [24]:
y_pred = model_fit.predict(X_test)
y_pred

array([4868.24970913, 4530.13471939, -541.59012667, 5037.307204  ,
       4699.19221426, 5206.36469887, 3853.90473992])

In [25]:
r2_score(y_test,y_pred)

0.45848491292476046